available_products:
  horai_20g:
    name: Horai - 20g
    url: https://ippodotea.com/collections/matcha/products/horai-no-mukashi
  ikuyo_100g:
    name: Ikuyo - 100g
    url: https://ippodotea.com/collections/matcha/products/ikuyo-100
  ikuyo_30g:
    name: Ikuyo - 30g
    url: https://ippodotea.com/collections/matcha/products/ikuyo
  kan_30g:
    name: Kan - 30g
    url: https://ippodotea.com/collections/matcha/products/kan
  sayaka_100g:
    name: Sayaka - 100g
    url: https://ippodotea.com/collections/matcha/products/sayaka-100g
  sayaka_40g:
    name: Sayaka - 40g
    url: https://ippodotea.com/collections/matcha/products/sayaka-no-mukashi
  ummon_20g:
    name: Ummon - 20g
    url: https://ippodotea.com/collections/matcha/products/ummon-no-mukashi-20g
  ummon_40g:
    name: Ummon - 40g
    url: https://ippodotea.com/collections/matcha/products/ummon-no-mukashi-40g
  wakaki_40g:
    name: Wakaki - 40g
    url: https://ippodotea.com/collections/matcha/products/wakaki-shiro
monitoring:
  check_interval: 15
  timeout: 10
telegram:
  # Token is now loaded from environment variable TELEGRAM_BOT_TOKEN
development:
  enabled: false
  # dev_user_id is now loaded from environment variable DEV_USER_ID
